USB_VID = 0x239A
USB_PID = 0x8058
USB_PRODUCT = "Serpente"
USB_MANUFACTURER = "arturo182"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = GD25Q32C
LONGINT_IMPL = NONE

# Save some more flash space
CIRCUITPY_ANALOGIO = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 0
CIRCUITPY_USB_MIDI = 0
CIRCUITPY_TOUCHIO = 0

CIRCUITPY_KEYPAD = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_HID
